### ISSUE TITLE
No toISOString function in...

### ISSUE THREAD

**Issue by runely** [jens-maus/node-ical#56]
When calling **async.fromURL(url, {}, (err, data))** this is thrown when *DTSTART* field in .ics file contains this: **"DTSTART;TZID="tzone://Microsoft/Custom":20200830T070000"**

```javascript
> Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: //Microsoft/Custom:20200831T180000, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/runely/source/calendarTest/node_modules/moment/moment.js:319:25)
    at configFromString (/Users/runely/source/calendarTest/node_modules/moment/moment.js:2536:19)
    at configFromInput (/Users/runely/source/calendarTest/node_modules/moment/moment.js:2978:13)
    at prepareConfig (/Users/runely/source/calendarTest/node_modules/moment/moment.js:2961:13)
    at createFromConfig (/Users/runely/source/calendarTest/node_modules/moment/moment.js:2928:44)
    at createLocalOrUTC (/Users/runely/source/calendarTest/node_modules/moment/moment.js:3022:16)
    at createLocal (/Users/runely/source/calendarTest/node_modules/moment/moment.js:3026:16)
    at hooks (/Users/runely/source/calendarTest/node_modules/moment/moment.js:16:29)
    at Object.END (/Users/runely/source/calendarTest/node_modules/node-ical/ical.js:440:21)
    at Object.handleObject (/Users/runely/source/calendarTest/node_modules/node-ical/ical.js:514:39)
No toISOString function in curr.start //Microsoft/Custom:20200831T180000
No toISOString function in curr.start //Microsoft/Custom:20200901T160000
No toISOString function in curr.start //Microsoft/Custom:20200901T190000
No toISOString function in exdate[name] //Microsoft/Custom:20201021T180000
No toISOString function in curr.start //Microsoft/Custom:20200902T180000
No toISOString function in curr.start //Microsoft/Custom:20200902T191500
No toISOString function in curr.start //Microsoft/Custom:20200904T090000
No toISOString function in curr.start //Microsoft/Custom:20200906T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20200906T090000
No toISOString function in exdate[name] //Microsoft/Custom:20200921T193000
No toISOString function in curr.start //Microsoft/Custom:20200907T193000
No toISOString function in exdate[name] //Microsoft/Custom:20201023T090000
No toISOString function in curr.start //Microsoft/Custom:20200911T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20200913T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20200920T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20200927T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201004T090000
No toISOString function in exdate[name] //Microsoft/Custom:20201020T090000
No toISOString function in curr.start //Microsoft/Custom:20201006T090000
No toISOString function in exdate[name] //Microsoft/Custom:20201021T070000
No toISOString function in curr.start //Microsoft/Custom:20201007T070000
No toISOString function in exdate[name] //Microsoft/Custom:20201022T090000
No toISOString function in curr.start //Microsoft/Custom:20201008T090000
No toISOString function in exdate[name] //Microsoft/Custom:20201019T070000
No toISOString function in curr.start //Microsoft/Custom:20201012T070000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201014T191500
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201015T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201020T160000
No toISOString function in curr.start //Microsoft/Custom:20201026T200000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201106T090000
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201117T090000
No toISOString function in curr.start //Microsoft/Custom:20201125T191500
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201130T200000
No toISOString function in curr.start //Microsoft/Custom:20201207T200500
No toISOString function in curr.recurrenceid //Microsoft/Custom:20201231T090000
No toISOString function in curr.start //Microsoft/Custom:20210104T070000
No toISOString function in exdate[name] //Microsoft/Custom:20210119T090000
No toISOString function in curr.start //Microsoft/Custom:20210105T090000
No toISOString function in curr.start //Microsoft/Custom:20210106T070000
```

**Comment by jens-maus** [comment]
Sorry, but this `tzone://Microsoft/Custom` look totally akward to me and out of specs. This doesn't see to be a correct timezone name/definition. So please explain where this comes from...

**Comment by runely** [comment]
This comes from an outlook.live.com ics url.

A snip from the beginning of the file, including VTIMEZONE, one normal event and one full day event (all non-full day events have this DTSTART and DTEND format. Full day events have the normal format):

```javascript
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:(**Masked away**)
BEGIN:VTIMEZONE
TZID:tzone://Microsoft/Custom
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:(**Masked away**)
SUMMARY:(**Masked away**)
DTSTART;TZID="tzone://Microsoft/Custom":20200830T070000
DTEND;TZID="tzone://Microsoft/Custom":20200830T080000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20201130T184302Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
BEGIN:VEVENT
UID:(**Masked away**)
SUMMARY:(**Masked away**)
DTSTART;VALUE=DATE:20210107
DTEND;VALUE=DATE:20210108
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20201130T184302Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DONOTFORWARDMEETING:FALSE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR

```

**Comment by runely** [comment]
Any thoughts on this?

**Comment by jens-maus** [comment]
> Any thoughts on this?

Well, the main thought is: Microsoft suxxs ;-) I really don't know what this `"tzone://Microsoft/Custom"`is... IMHO this looks like they are violating the standard by introducing yet-another nonsense extension just for their own need.

**Comment by runely** [comment]
Apparently they do.. A quick [Google search](https://www.google.com/search?q=tzone%3A%2F%2Fmicrosoft%2Fcustom&oq=tzone%3A%2F%2Fmicrosoft%2Fcustom) for `"tzone://Microsoft/Custom"` shows this has been around for quite some time. Some people replaces it with the correct timezone, however that isn't an option here as the correct timezone isn't present... I understand the problem in fixing this...

**Comment by jens-maus** [comment]
Perhaps @sdetweil has some idea how to integrate support for these strange M$ `zone://Microsoft/Custom` TZID definitions or could come up with a work around as he has implemented all this windows TZID recognition lately in node-ical

**Comment by sdetweil** [comment]
Currently the implementation does not compare the event  tzones to the tzones defined in the ics file. As they are expected to map to real world tzones already defined. 

None of the applications I support,  use those values either.

**Comment by runely** [comment]
[Microsoft Graph documentation states](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/event.md#properties): `A value of "tzone://Microsoft/Custom" indicates that a legacy custom time zone was set in desktop Outlook`.

If i understand this correctly, then there’s no way to know which tzone the event is created in. So maybe `node-ical` should treat these events as local time instead. It’s better that it works than crashing.

I can’t imagine this would cause any problems as long as it’s documented somewhere.

**Comment by sdetweil** [comment]
@runely thats seems like a reasonable approach..

**Comment by sdetweil** [comment]
i am trying to fix this and the no DTEND  issue..
having a devil of a time with no end... 
i 'thought' it would be code in the END: case 
but the start date doesn't come thru...
