### ISSUE TITLE
No toISOString function in exdate[name]

### ISSUE THREAD

**Issue by runely** [jens-maus/node-ical#75]
This is thrown when an EXDATE is date only: `EXDATE:20400116`

```javascript
TypeError: No toISOString function in exdate[name]
    at /node_modules/node-ical/ical.js:278:17
    at Array.forEach (<anonymous>)
    at Object.EXDATE (/node_modules/node-ical/ical.js:270:11)
    at Object.handleObject (/node_modules/node-ical/ical.js:521:39)
    at Object.parseLines (/node_modules/node-ical/ical.js:575:18)
    at Object.parseICS (/node_modules/node-ical/ical.js:628:12)
    at Request._callback (/node_modules/node-ical/node-ical.js:114:12)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
```

**Comment by runely** [comment]
Added a [PR](https://github.com/jens-maus/node-ical/pull/77) with an ics file so there can be made a test, and this issue can be resolved

**Comment by camrun91** [comment]
@jens-maus  I can confirm I am getting this same error.

**Comment by runely** [comment]
@jens-maus In this latest version, `0.12.7`, this problem has come to the surface because the error is now thrown instead of logged to the console: [replace all console.error() with proper "throw Error" returns to return](https://github.com/jens-maus/node-ical/commit/7cdb3fbca01999c4fb7f3071a75357b84335f251#diff-a717da36dca416b92146c74d0e6a1cae778967192eda55915710200af50ec829R278)

**Comment by runely** [comment]
Updated the [PR](https://github.com/jens-maus/node-ical/pull/77) with a fix that works with the invalid calendar as well as all my calendars

**Comment by jens-maus** [comment]
Thanks for the PR. Merge it now after having applied a small fix/improvement.
